// Original name
export type Dict = { [key: string]: string };

export const bankingIncomeStatementDict: Dict = {
  interest_income: "Interest Income",
  interest_expense: "Interest Expense",
  net_interest_income: "Net Interest Income",
  fee_and_commission_income: "Fee and Commission Income",
  fee_and_commission_expense: "Fee and Commission Expense",
  net_fee_and_commission_income: "Net Fee and Commission Income",
  net_interest_fee_and_commission_income:
    "Net Interest, Fee, and Commission Income",
  net_trading_income: "Net Trading Income",
  other_operating_income: "Other Operating Income",
  total_operating_income: "Total Operating Income",
  impairment_charge_reversal_for_loans_and_other_losses:
    "Impairment Charge/Reversal for Loans and Other Losses",
  interest_expenses: "Interest Expenses",
  fees_and_commission_income: "Fees and Commission Incomes",
  fees_and_commission_expenses: "Fees and Commission Expenses",
  net_operating_income: "Net Operating Income",
  personnel_expense: "Personnel Expenses",
  other_operating_expenses: "Other Operating Expenses",
  depreciation_amortization: "Depreciation and Amortization",
  operating_profit: "Operating Profit",
  non_operating_income: "Non Operating Income",
  non_operating_incomes: "Non Operating Incomes",
  non_operating_expense: "Non Operating Expense",
  non_operating_expenses: "Non Operating Expenses",
  profit_before_income_tax: "Profit Before Income Tax",
  current_tax: "Current Tax",
  deferred_tax: "Deferred Tax",
  profit_loss_for_the_period: "Net Profit",
  impairment_charge_or_reversal_for_loans_and_other_losses:
    "Impairment charge/(reversal) for loans and other losses",
};
export const bankingBalanceSheetDict: Dict = {
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  due_from_nepal_rastra_bank: "Due from Nepal Rastra Bank",
  placement_with_bank_and_financial_institutions:
    "Placement with Bank and Financial Institutions",
  derivative_financial_instruments: "Derivative Financial Instruments",
  assets_derivative_financial_instruments:
    "Assets: Derivative Financial Instruments",
  other_trading_assets: "Other Trading Assets",
  loan_and_advances_to_bfs:
    "Loan and Advances to Bank and Financial Institutions",
  loan_and_advances_to_customers: "Loans and Advances to Customers",
  investment_securities: "Investment Securities",
  current_tax_asset: "Current Tax Asset",
  investment_in_subsidiaries: "Investment in Subsidiaries",
  investment_in_associates: "Investment in Associates",
  investment_property: "Investment Property",
  property_and_equipment: "Property and Equipment",
  goodwill_and_intangible_assets: "Goodwill and Intangible Assets",
  deferred_tax_assets: "Deferred Tax Assets",
  other_assets: "Other Assets",
  total_assets: "Total Assets",
  due_to_bank_and_financial_institutions:
    "Due to Bank and Financial Institutions",
  due_to_nepal_rastra_bank: "Due to Nepal Rastra Bank",
  liabilities_derivative_financial_instruments:
    "Liabilities: Derivative Financial Instruments",
  deposit_from_customers: "Deposits from Customers",
  borrowings: "Borrowings",
  current_tax_liabilities: "Current Tax Liabilities",
  provisions: "Provisions",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  other_liabilities: "Other Liabilities",
  debt_securities_issued: "Debt Securities Issued",
  subordinated_liabilities: "Subordinated Liabilities",
  total_liabilities: "Total Liabilities",
  share_capital: "Share Capital",
  share_premium: "Share Premium",
  retained_earnings: "Retained Earnings",
  reserves: "Reserves",
  total_equity: "Total Equity",
  total_liabilities_and_equity: "Total Liabilities and Equity",
};
export const bankRatiosDict: Dict = {
  capital_fund_to_rwa: "Capital Fund to RWA",
  tier_i_capital_to_rwa: "Tier-I capital to RWA",
  cet_i_capital_to_rwa: "CET I Capital to RWA",
  non_performing_loan_npl_to_total_loan:
    "Non-Performing Loan (NPL) to Total Loan",
  net_non_performing_loan_to_total_loan:
    "Net Non-Performing Loan to Total Loan",
  total_loan_loss_provision_to_total_npl:
    "Total loan loss provision to Total NPL",
  cost_of_funds: "cost of Funds",
  credit_to_deposit_ratio: "Credit to Deposit Ratio",
  base_rate_monthly: "Base Rate (monthly)",
  interest_rate_spread: "Interest Rate Spread",
  return_on_equity_annualized: "Return on Equity (Annualized)",
  return_on_assets_annualized: "Return on Assets (Annualized)",
};
export const microFinanceIncomeStatementDict = {
  interest_income: "Interest Income",
  interest_expense: "Interest Expense",
  net_interest_income: "Net Interest Income",
  fee_and_commission_income: "Fee and Commission Income",
  fee_and_commission_expense: "Fee and Commission Expense",
  net_fee_and_commission_income: "Net Fee and Commission Income",
  net_interest_fee_and_commission_income:
    "Net Interest, Fee, and Commission Income",
  net_trading_income: "Net Trading Income",
  other_operating_income: "Other Operating Income",
  total_operating_income: "Total Operating Income",
  impairment_charge_reversal_for_loans_and_other_losses:
    "Impairment Charge/Reversal for Loans and Other Losses",
  personnel_expense: "Personnel Expense",
  other_operating_expenses: "Other Operating Expenses",
  depreciation_amortization: "Depreciation and Amortization",
  operating_profit: "Operating Profit",
  non_operating_income: "Non Operating Income",
  non_operating_expense: "Non Operating Expense",
  profit_before_income_tax: "Profit Before Income Tax",
  current_tax: "Current Tax",
  profit_loss_for_the_period: "Net Profit",
};
export const microFinanceBalanceSheetDict = {
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  due_from_nepal_rastra_bank: "Due from Nepal Rastra Bank",
  placement_with_bank_and_financial_institutions:
    "Placement with Bank and Financial Institutions",
  assets_derivative_financial_instruments:
    "Assets: Derivative Financial Instruments",
  other_trading_assets: "Other Trading Assets",
  loan_and_advances_to_bfs:
    "Loan and Advances to Bank and Financial Institutions",
  loan_and_advances_to_customers: "Loans and Advances to Customers",
  investment_securities: "Investment Securities",
  current_tax_asset: "Current Tax Asset",
  property_and_equipment: "Property and Equipment",
  goodwill_and_intangible_assets: "Goodwill and Intangible Assets",
  other_assets: "Other Assets",
  total_assets: "Total Assets",
  due_to_bank_and_financial_institutions:
    "Due to Bank and Financial Institutions",
  deposit_from_customers: "Deposits from Customers",
  borrowings: "Borrowings",
  current_tax_liabilities: "Current Tax Liabilities",
  other_liabilities: "Other Liabilities",
  total_liabilities: "Total Liabilities",
  share_capital: "Share Capital",
  retained_earnings: "Retained Earnings",
  reserves: "Reserves",
  total_equity: "Total Equity",
  total_liabilities_and_equity: "Total Liabilities and Equity",
};
export const insuranceBalanceSheetDict: Dict = {
  goodwill_intangible_assets: "Goodwill & Intangible Assets",
  property_and_equipment: "Property and Equipment",
  investment_properties: "Investment Properties",
  deferred_tax_assets: "Deferred Tax Assets",
  investment_in_subsidiaries: "Investment in Subsidiaries",
  investment_in_associates: "Investment in Associates",
  investments: "Investments",
  loans: "Loans",
  reinsurance_assets: "Reinsurance Assets",
  current_tax_assets: "Current Tax Assets",
  insurance_receivables: "Insurance Receivables",
  other_assets: "Other Assets",
  other_financial_assets: "Other Financial Assets",
  cash_and_cash_equivalent: "Cash and Cash Equivalent",
  total_assets: "Total Assets",
  share_capital: "Share Capital",
  share_application_money_pending_allotment:
    "Share Application Money Pending Allotment",
  share_premium: "Share Premium",
  special_reserves: "Special Reserves",
  catastrophe_reserves: "Catastrophe Reserves",
  retained_earnings: "Retained Earnings",
  other_equity: "Other Equity",
  total_equity: "Total Equity",
  provisions: "Provisions",
  gross_insurance_contract_liabilities: "Gross Insurance Contract Liabilities",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  insurance_payable: "Insurance Payable",
  current_tax_liabilities: "Current Tax Liabilities",
  borrowings: "Borrowings",
  other_liabilities: "Other Liabilities",
  other_financial_liabilities: "Other Financial Liabilities",
  total_liabilities: "Total Liabilities",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const insuranceIncomeStatementDict: Dict = {
  gross_earned_premiums: "Gross Earned Premiums",
  premiums_ceded: "Premiums Ceded",
  net_earned_premiums: "Net Earned Premiums",
  commission_income: "Commission Income",
  other_direct_income: "Other Direct Income",
  income_from_investments_and_loans: "Income from Investments & Loans",
  net_gain_loss_on_fair_value_changes: "Net Gain/ (Loss) on Fair Value Changes",
  net_realised_gains_losses: "Net Realised Gains/ (Losses)",
  other_income: "Other Income",
  total_income: "Total Income",
  gross_claims_paid: "Gross Claims Paid",
  claims_ceded: "Claims Ceded",
  gross_change_in_contract_liabilities: "Gross Change in Contract Liabilities",
  change_in_contract_liabilities_ceded_to_reinsurers:
    "Change in Contract Liabilities Ceded to Reinsurers",
  net_claims_incurred: "Net Claims Incurred",
  commission_expenses: "Commission Expenses",
  service_fees: "Service Fees",
  other_direct_expenses: "Other Direct Expenses",
  employee_benefits_expenses: "Employee Benefits Expenses",
  depreciation_and_amortization_expenses:
    "Depreciation and Amortization Expenses",
  impairment_losses: "Impairment Losses",
  other_operating_expenses: "Other Operating Expenses",
  finance_cost: "Finance Cost",
  total_expenses: "Total Expenses",
  net_profit_loss_before_share_of_net_profits_of_associates_accounted_for_using_equity_method_and_tax:
    "Net Profit/(Loss) For The Year Before Share of Net Profits of Associates Accounted for Using Equity Method and Tax",
  share_of_net_profit_of_associates_accounted_using_equity_method:
    "Share of Net Profit of Associates accounted using Equity Method",
  profit_before_tax: "Profit Before Tax",
  income_tax_expense: "Income Tax Expense",
  net_profit_loss_for_the_year: "Net Profit/(Loss) For The Year",
  basic_eps: "Basic EPS",
  diluted_eps: "Diluted EPS",
};
export const nonelifeInsuranceRatiosDict: Dict = {
  total_issued_policy_count: "Total Issued Policy Count",
  total_renewed_policy_count: "Total Renewed Policy Count",
  total_claim_paid_count: "Total Claim Paid Count",
  outstanding_claims_count: "Outstanding Claims Count",
  gross_outstanding_claim_including_ibnr_and_ibner_amount:
    "Gross Outstanding Claim including IBNR and IBNER (amount)",
  net_outstanding_claim_including_ibnr_and_ibner_amount:
    "Net Outstanding Claim including IBNR and IBNER (amount)",
  margin_over_best_estimate_mobe: "Margin Over Best Estimate (MOBE)",
  unearned_premium_reserve_amount: "Unearned Premium Reserve (Amount)",
  unexpired_risk_reserve_amount: "Unexpired Risk Reserve (Amount)",
  earthquake_premium_reserve_amount: "Earthquake Premium Reserve (Amount)",
  long_term_investments_amount: "Long Term Investments (Amount)",
  short_term_investments_amount: "Short Term Investments (Amount)",
  direct_premium_amount: "Direct Premium (Amount)",
  investment_in_cost_amount: "Investment in Cost (Amount)",
  solvency_margin_ratio_based_on_audited_fy_2079_80:
    "Solvency Margin Ratio (Based on Audited FY 2079/80)",
};
export const lifeInsuranceRatiosDict: Dict = {
  total_inforce_policy_count: "Total inforce Policy count",
  total_no_of_policies_issued_during_the_period:
    "Total no. of policies issued during the period",
  first_year_premium_including_single_premium:
    "First Year Premium (Including Single Premium)",
  single_premium: "Single Premium",
  renewal_premium: "Renewal Premium",
  total_benefits_and_claims_paid_in_count:
    "Total Benefits and Claims Paid in Count",
  outstanding_benefits_and_claims_in_count:
    "Outstanding Benefits and Claims in Count",
  gross_claim_outstanding_amount: "Gross Claim Outstanding (Amount)",
  declared_bonus_rate_fiscal_year_2079_2080:
    "Declared Bonus rate (Fiscal Year 2079/2080)",
  interim_bonus_rate: "Interim bonus rate",
  long_term_investments_amount: "Long Term Investments (Amount)",
  short_term_investments_amount: "Short Term Investments (Amount)",
  policyholders_loan: "Policyholders Loan",
  investment_in_cost_value: "Investment in Cost Value",
  unearned_premium_reserve_for_term_policies_amount:
    "Unearned Premium Reserve for Term Policies (Amount)",
  solvency_margin_ratio_fy_2079_080: "Solvency Margin Ratio (FY 2079/080)",
};
export const htBalanceSheetDict: Dict = {
  property_plant_and_equipment: "Property, Plant and Equipment",
  intangible_asset: "Intangible Asset",
  capital_work_in_progress: "Capital Work in Progress",
  right_of_use_of_asset: "Right of Use of Asset",
  long_term_investment: "Long term Investment",
  deferred_tax_asset: "Deferred tax asset",
  total_non_current_asset: "Total of Non-Current Asset",
  inventories: "Inventories",
  account_receivables: "Account Receivables",
  cash_and_cash_equivalent: "Cash & Cash Equivalent",
  loans_and_advances: "Loans & Advances",
  other_current_assets: "Other Current Assets",
  total_current_asset: "Total of Current Asset",
  total_asset: "Total Asset",
  share_capital: "Share Capital",
  reserve_and_surplus: "Reserve and Surplus",
  total_equity_reserve_and_surplus: "Total Equity, Reserve and Surplus",
  long_term_borrowings: "Long-term borrowings",
  deferred_tax_liabilities: "Deferred Tax Liabilites",
  lease_liability: "Lease Liability",
  total_of_non_current_liabilities: "Total of Non-Current Liabilities",
  duties_and_taxes: "Duties & Taxes",
  account_payable: "Account payable",
  other_current_liabilities: "Other Current Liabilities",
  total_current_liabilities: "Total Current Liabilities",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const htIncomeStatementDict: Dict = {
  revenue_from_operation: "Revenue from Operation",
  cost_of_sales: "Cost of sales",
  gross_income: "Gross Income",
  other_income: "Other Income",
  expenses: "Expenses",
  employee_benefits_expenses: "Employee Benefits Expenses",
  administrative_and_other_expenses: "Administrative and Other Expenses",
  total_expenses: "Total Expenses",
  profit_before_interest_depreciation_and_tax:
    "Profit Before Interest, Depreciation and Tax",
  finance_costs: "Finance costs",
  profit_before_depreciation_and_tax: "Profit Before Depreciation and Tax",
  depreciation_and_amortization_expenses:
    "Depreciation and Amortization Expenses",
  profit_before_extra_ordinary_items_and_taxes:
    "Profit before extra ordinary items and taxes",
  extra_ordinary_item: "Extra ordinary item",
  profit_before_taxes: "Profit before taxes",
  tax_expenses: "Tax Expenses",
  current_tax: "Current Tax",
  deferred_tax_income_expenses: "Deferred Tax (Income)/Expenses",
  profit_loss_for_the_period_from_continuing_operations:
    "Profit (Loss) for the period from continuing operations",
  profit_loss_from_discontinuing_operations:
    "Profit/(Loss) from dis-continuing operations",
  tax_expenses_of_discontinuing_operations:
    "Tax expenses of dis-continuing operations",
  profit_loss_for_the_period_from_discontinuing_operations:
    "Profit (Loss) for the period from dis-continuing operations",
  profit_loss_for_the_period: "Profit/(Loss) for the period",
  earning_per_equity_share: "Earning per equity share:",
  diluted_earning_per_share: "Diluted Earning per share",
};
export const mpIncomeStatementDict: Dict = {
  revenue_from_operation: "Revenue from Operation",
  other_income: "Other Income",
  total_income: "Total Income",
  cost_of_materials: "Cost of Materials",
  manufacturing_expenses: "Manufacturing Expenses",
  administrative_expenses: "Administrative Expenses",
  selling_distribution_expenses: "Selling/Distribution Expenses",
  depreciation: "Depreciation",
  financial_expenses: "Financial Expenses",
  other_expenses: "Other Expenses",
  operating_profit: "Operating Profit",
  provision_obsolescence: "Provision Obsolescence",
  provision_write_off: "Provision Write Off",
  housing_fund_allocation: "Housing Fund Allocation",
  profit_before_provision_bonus: "Profit Before Provision Bonus",
  provision_for_bonus: "Provision for Bonus",
  profit_before_tax: "Profit Before Tax",
  provision_taxation: "Provision Taxation",
  current_tax: "Current Tax",
  deferred_tax: "Deferred Tax",
  net_profit: "Net Profit",
};
export const mpBalanceSheetDict: Dict = {
  share_capital: "Share Capital",
  share_premium: "Share Premium",
  retained_earnings: "Retained Earnings",
  total_equity: "Total Equity",
  total_liabilities_and_equity: "Total Liabilities and Equity",
  inventories: "Inventories",
  trade_receivables: "Trade Receivables",
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  others: "Others",
  other_current_assets: "Other Current Assets",
  income_tax_assets_net: "Income Tax Assets (Net)",
  total_current_assets: "Total Current Assets",
  total_assets: "Total Assets",
  property_plant_and_equipment: "Property, Plant and Equipment",
  intangible_assets: "Intangible Assets",
  investment_in_subsidiary: "Investment in Subsidiary",
  investment_in_associates: "Investment in Associates",
  deferred_tax_assets: "Deferred Tax Assets",
  other_non_current_assets: "Other Non-Current Assets",
  total_non_current_assets: "Total Non Current Assets",
  trade_payables: "Trade Payables",
  short_term_borrowings: "Short Term Borrowings",
  other_financial_liabilities: "Other Financial Liabilities",
  other_current_liabilities: "Other Current Liabilities",
  provisions: "Provisions",
  income_tax_liabilities_net: "Income Tax Liabilities (Net)",
  total_current_liabilities: "Total Current Liabilities",
  total_liabilities: "Total Liabilities",
  long_term_borrowings: "Long Term Borrowings",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  other_non_current_liabilities: "Other Non-Current Liabilities",
  total_non_current_liabilities: "Total Non Current Liabilities",
};
// investments
export const investmentIncomeStatementDict: Dict = {
  interest_income: "Interest Income",
  dividend_income: "Dividend Income",
  fees_and_commission_income: "Fees and Commission Income",
  other_income: "Other Income",
  total_income: "Total Income",
  operational_expenses: "Operational Expenses",
  provisions_for_investment_risks_and_other_losses:
    "Provisions for Investment Risks and Other Losses",
  misc_expenses: "Misc Expenses",
  total_operating_expenses: "Total operating Expenses",
  ebitda: "EBITDA",
  depreciation_and_amortization: "Depreciation and Amortization",
  ebit: "EBIT",
  financial_expenses: "Financial Expenses",
  profit_before_bonus_and_taxes: "Profit Before Bonus and Taxes",
  provision_for_bonus: "Provision for Bonus",
  profit_before_taxes: "Profit Before Taxes",
  provision_for_taxes: "Provision for Taxes",
  net_profit: "Net Profit",
};
export const investmentBalanceSheetDict: Dict = {
  property_plant_and_equipment: "Property, Plant & Equipment",
  accumulated_depreciation: "Accumulated Depreciation",
  net_fixed_assets: "Net Fixed Assets",
  investments: "Investments",
  loans_extended: "Loans Extended",
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  term_deposits: "Term Deposits",
  other_current_assets: "Other Current Assets",
  misc_assets: "Misc Assets",
  total_uses_of_funds: "Total Uses of Funds",
  fund_deposits: "Fund Deposits",
  loans: "Loans",
  total_long_term_liabilities: "Total Long Term Liabilities",
  current_liabilities_and_provision: "Currrent Liabilities and Provision",
  trade_and_other_payables: "Trade and Other Payables",
  dividend_payable: "Dividend Payable",
  other_liabilities_and_provisions: "Other Liabilities and Provisions",
  corporate_income_tax_liabilities: "Corporate Income Tax Liabilities",
  provisions_for_possible_losses: "Provisions for Possible Losses",
  current_liabilities_and_provisions: "Current Liabilities and Provisions",
  total_sources_of_funds: "Total Sources of Funds",
  paid_up_capital: "Paid Up Capital",
  share_premium: "Share Premium",
  preference_shares: "Preference Shares",
  reserves_and_surplus: "ReservesAndSurplus",
  total_equity: "Total Equity",
};
export const investmentRatiosDict: Dict = {
  earnings_per_share: "Earnings Per Share",
  book_value_per_share: "Book Value per Share",
  return_on_equity: "Return on Equity",
  return_on_asset: "Return on Asset",
  return_on_investment: "Return on Investment",
  operating_profit_margin: "Operating Profit Margin",
  net_profit_margin: "Net Profit Margin",
  market_cap: "Market Cap",
  price_earnings: "Price/Earnings",
  price_book: "Price/Book",
};
// hydro
export const hydroBalanceSheetDict: Dict = {
  share_capital: "Share Capital",
  premium: "Premium",
  reserves: "Reserves",
  long_term_liabilities: "Long Term Liabilities",
  total_funds: "Total Funds",
  fixed_assets: "Fixed Assets",
  depreciation: "Depreciation",
  net_fixed_assets: "Net Fixed Assets",
  non_core_assets: "Non Core Assets",
  investments: "Investments",
  work_in_progress: "Work In Progress",
  cash: "Cash",
  receivables: "Receivables",
  advances_prepayments_loans_deposits_and_other_current_assets:
    "Advances Prepayments Loans Deposits and other Current Assets",
  inventory: "Inventory",
  total_current_assets: "Total Current Assets",
  short_term_liabilities: "Short Term Liabilities",
  deferred_liabilities: "Deferred Liabilities",
  total_short_term_liabilities: "Total Short-Term Liabilities",
  application_of_funds: "Application of Funds",
};
export const hydroIncomeStatementDict: Dict = {
  energy_sales: "Energy Sales",
  cost_of_production: "Cost of Production",
  gross_profit: "Gross Profit",
  dividend_income: "Dividend Income",
  forex_gain_loss: "Forex Gain/Loss",
  other_income: "Other Income",
  admin_expenses: "Admin Expenses",
  operating_profit: "Operating Profit",
  interest_expense: "Interest Expense",
  depreciation: "Depreciation",
  provisions: "Provisions",
  profit_before_tax: "Profit Before Tax",
  taxes: "Taxes",
  bonus_and_csr: "Bonus and CSR",
  net_profit: "Net Profit",
  profitability_ratios: "Profitability Ratios",
  earnings_per_share: "Earnings Per Share",
  book_value_per_share: "Book Value per Share",
  ebitda: "EBITDA",
  gross_profit_margin: "Gross Profit Margin",
  operating_profit_margin: "Operating Profit Margin",
  net_profit_margin: "Net Profit Margin",
  management_efficiency_ratios: "Management Efficiency Ratios",
  return_on_equity: "Return on Equity",
  return_on_asset: "Return on Asset",
  return_on_capital_employed: "Return on Capital Employed",
  debt_equity: "Debt-Equity",
  current_ratio: "Current Ratio",
  valuation_ratios: "Valuation Ratios",
  market_cap: "Market Cap",
  enterprise_value_ev: "Enterprise Value (EV)",
  price_earnings: "Price/Earnings",
  price_book: "Price/Book",
  price_revenue: "Price/Revenue",
  ev_ebitda: "Ev/EBITDA",
};

// others

export const hrlIncomeStatementDict: Dict = {
  gross_earned_premiums: "Gross Earned Premiums",
  premiums_ceded: "Premiums Ceded",
  net_earned_premiums: "Net Earned Premiums",
  commission_income: "Commission Income",
  other_direct_income: "Other Direct Income",
  income_from_investments_and_loans: "Income from Investments & Loans",
  net_gain_loss_on_fair_value_changes: "Net Gain/(Loss) on Fair Value Changes",
  net_realised_gains_losses: "Net Realised Gains/(Losses)",
  other_income: "Other Income",
  total_income: "Total Income",
  gross_claims_paid: "Gross Claims Paid",
  claims_ceded: "Claims Ceded",
  gross_change_in_contract_liabilities: "Gross Change in Contract Liabilities",
  change_in_contract_liabilities_ceded_to_reinsurers:
    "Change in Contract Liabilities Ceded to Reinsurers",
  net_claims_incurred: "Net Claims Incurred",
  commission_expenses: "Commission Expenses",
  service_fees: "Service Fees",
  other_direct_expenses: "Other Direct expenses",
  employee_benefits_expenses: "Employee Benefits Expenses",
  depreciation_and_amortization_expenses:
    "Depreciation and Amortization Expenses",
  impairment_losses: "Impairment Losses",
  other_operating_expenses: "Other Operating Expenses",
  finance_cost: "Finance Cost",
  total_expenses: "Total Expenses",
  net_profit_loss_for_the_year_before_share_of_net_profits_of_associates_accounted_for_using_equity_method_and_tax:
    "Net Profit/(Loss) For The Year Before Share of Net Profits of Associates Accounted for Using Equity Method and Tax",
  share_of_net_profit_of_associates_accounted_using_equity_method:
    "Share of Net Profit of Associates accounted using Equity Method",
  profit_before_tax: "Profit Before Tax",
  income_tax_expenses: "Income Tax Expenses",
  net_profit_loss_for_the_year: "Net Profit/(Loss) For The Year",
  basic_eps: "Basic EPS",
  diluted_eps: "Diluted EPS",
};
export const hrlBalanceSheetDict: Dict = {
  goodwill_intangible_assets: "Goodwill & Intangible Assets",
  property_and_equipment: "Property and Equipment",
  investment_properties: "Investment Properties",
  deferred_tax_assets: "Deferred Tax Assets",
  investment_in_subsidiaries: "Investment in Subsidiaries",
  investment_in_associates: "Investment in Associates",
  investments: "Investments",
  loans: "Loans",
  reinsurance_assets: "Reinsurance Assets",
  current_tax_assets: "Current Tax Assets",
  insurance_receivables: "Insurance Receivables",
  other_assets: "Other Assets",
  other_financial_assets: "Other Financial Assets",
  cash_and_cash_equivalent: "Cash and Cash Equivalent",
  total_assets: "Total Assets",
  share_capital: "Share Capital",
  share_application_money_pending_allotment:
    "Share Application Money Pending Allotment",
  share_premium: "Share Premium",
  special_reserves: "Special Reserves",
  catastrophe_reserves: "Catastrophe Reserves",
  retained_earnings: "Retained Earnings",
  other_equity: "Other Equity",
  non_controlling_interest: "Non Controlling Interest",
  total_equity: "Total Equity",
  provisions: "Provisions",
  gross_insurance_contract_liabilities: "Gross Insurance Contract Liabilities",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  insurance_payable: "Insurance Payable",
  current_tax_liabilities: "Current Tax Liabilities",
  borrowings: "Borrowings",
  other_liabilities: "Other Liabilities",
  other_financial_liabilities: "Other Financial Liabilities",
  total_liabilities: "Total Liabilities",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const ntcIncomeStatementDict: Dict = {
  revenue_from_contract_with_customers: "Revenue from contract with customers",
  finance_income: "Finance Income",
  other_income: "Other Income",
  total_income: "Total Income",
  employee_benefit_expenses: "Employee Benefit Expenses",
  operation_and_maintenance_costs: "Operation and Maintenance Costs",
  sales_channel_marketing_and_promotion_costs:
    "Sales Channel, Marketing and Promotion Costs",
  office_operation_expenses: "Office Operation Expenses",
  regulatory_fees_charges_and_renewals: "Regulatory Fees, Charges and Renewals",
  foreign_exchange_loss_gain: "Foreign Exchange (Loss)/Gain",
  shares_of_results_of_associates: "Shares of results of associates",
  earning_before_interest_tax_depreciation_and_amortisation_ebitda:
    "Earning Before Interest, Tax, Depreciation & Amortisation(EBITDA)",
  finance_cost: "Finance Cost",
  depreciation: "Depreciation",
  amortisation: "Amortisation",
  impairments_net_of_reversals: "Impairments - net of reversals",
  profit_before_tax: "Profit Before Tax",
  income_tax_expenses: "Income Tax Expenses",
  current_income_tax: "Current Income Tax",
  deferred_taxes: "Deferred Taxes",
  deferred_taxes_due_to_change_in_corporate_tax_rate:
    "Deferred Taxes- Due to Change in Corporate Tax Rate",
  profit_for_the_period: "Profit For the Period",
};
export const ntcBalanceSheetDict: Dict = {
  intangible_assets: "Intangible Assets",
  property_plant_and_equipment: "Property, Plant and Equipment",
  right_of_use_rou_assets: "Right of Use (ROU) Assets",
  capital_work_in_progress: "Capital Work-in-Progress",
  long_term_loan_and_advances: "Long Term Loan and Advances",
  investment: "Investment",
  deferred_tax_asset: "Deferred Tax Asset",
  employee_loan: "Employee Loan",
  contract_cost_assets: "Contract Cost Assets",
  total_non_current_assets: "Total Non-Current Assets",
  inventory: "Inventory",
  prepayments_and_non_financial_assets: "Prepayments & Non-Financial Assets",
  current_tax_assets: "Current Tax Assets",
  accruals_advance_others_receivables: "Accruals, Advance & Others Receivables",
  trade_receivable: "Trade Receivable",
  current_investment: "Investment",
  cash_and_cash_equivalents: "Cash & Cash Equivalents",
  total_current_assets: "Total Current Assets",
  total_assets: "Total Assets",
  share_capital: "Share Capital",
  reserve_and_surplus: "Reserve and Surplus",
  total_equity_attributable_to_equityholders:
    "Total Equity attributable to Equityholders",
  non_controlling_interest: "Non Controlling Interest",
  total_equity: "Total Equity",
  net_employment_benefits: "Post Employment Benefits",
  deferred_government_grant: "Deferred Government Grant",
  subscriber_deposits: "Subscriber Deposits",
  gsm_license_renewal_fee_liability: "GSM License Renewal Fee Liability",
  lease_liability: "Lease Liability",
  total_non_current_liabilities: "Total Non-Current Liabilities",
  current_tax_liabilities: "Current Tax Liabilities",
  provisions: "Provisions",
  current_liabilities: "Current Liabilities",
  other_non_financial_liabilities: "Other Non-Financial Liabilities",
  total_current_liabilities_and_provisions:
    "Total Current Liabilities and Provisions",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const mkchBalanceSheetDict: Dict = {
  property_plant_and_equipments: "Property, Plant and Equipments",
  intangible_assets: "Intangible Assets",
  trade_and_other_receivables: "Trade and Other Receivables",
  investment: "Investment",
  total_non_current_assets: "Total Non-Current Assets",
  inventories: "Inventories",
  income_tax_assets: "Income Tax Assets",
  prepayments_advances_and_deposits: "Prepayments/Advances and Deposits",
  cash_and_cash_equivalents: "Cash & Cash Equivalents",
  deferred_tax_assets: "Deferred Tax Assets",
  total_current_assets: "Total Current Assets",
  total_assets: "Total Assets",
  equity_share_capital: "Equity Share Capital",
  other_equity: "Other Equity",
  total_equity: "Total Equity",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  total_non_current_liabilities: "Total Non-Current Liabilities",
  trade_and_other_financial_liabilities:
    "Trade and Other Financial Liabilities",
  provisions: "Provisions",
  short_term_loan: "Short Term Loan",
  total_current_liabilities: "Total Current Liabilities",
  total_equity_and_liabilities: "Total equity and Liabilities",
};
export const mkchIncomeStatementDict: Dict = {
  revenue_from_operations: "Revenue from Operations",
  less_cost_of_goods_sold: "Less: Cost of Goods Sold",
  gross_profit: "Gross Profit",
  other_income: "Other Income",
  total_income: "Total Income",
  operating_expenses: "Operating Expenses",
  personnel_expenses: "Personnel Expenses",
  other_operating_expenses: "Other Operating Expenses",
  financial_expenses: "Financial Expenses",
  depreciation_and_amortisation_expenses:
    "Depreciation and Amortisation Expenses",
  total_operating_expenses: "Total Operating Expenses",
  non_operating_income_expenses: "Non Operating (Income)/Expenses",
  total_expenses: "Total Expenses",
  profit_before_income_tax: "Profit before Income Tax",
  tax_expenses: "Tax Expenses",
  current_tax: "Current Tax",
  deferred_tax: "Deferred Tax",
  total_tax_expenses: "Total Tax Expenses",
  profit_for_the_period: "Profit for the Period",
  basic_earning_per_share_eps: "Basic Earning Per Share (EPS)",
};
export const nricIncomeStatementDict: Dict = {
  gross_earned_premiums: "Gross Earned Premiums",
  premiums_ceded: "Premiums Ceded",
  net_earned_premiums: "Net Earned Premiums",
  commission_income: "Commission Income",
  other_direct_income: "Other Direct Income",
  income_from_investments_and_loans: "Income from Investments and Loans",
  net_gain_loss_on_fair_value_changes: "Net Gain/(Loss) on Fair Value Changes",
  net_realised_gains_losses: "Net Realised Gains/(Losses)",
  other_income: "Other Income",
  total_income: "Total Income",
  gross_claims_paid: "Gross Claims Paid",
  claims_ceded: "Claims Ceded",
  gross_change_in_contract_liabilities: "Gross Change in Contract Liabilities",
  change_in_contract_liabilities_ceded_to_reinsurers:
    "Change in Contract Liabilities Ceded to Reinsurers",
  net_claims_incurred: "Net Claims Incurred",
  commission_expenses: "Commission Expenses",
  service_fees: "Service Fees",
  other_direct_expenses: "Other Direct expenses",
  employee_benefits_expenses: "Employee Benefits Expenses",
  depreciation_and_amortization_expenses:
    "Depreciation and Amortization Expenses",
  impairment_losses: "Impairment Losses",
  other_operating_expenses: "Other Operating Expenses",
  finance_cost: "Finance Cost",
  total_expenses: "Total Expenses",
  net_profit_loss_before_associates_and_tax:
    "Net Profit/(Loss) For The Year Before Share of Net Profits of Associates Accounted for Using Equity Method and Tax",
  share_of_net_profit_of_associates:
    "Share of Net Profit of Associates accounted using Equity Method",
  profit_before_tax: "Profit Before Tax",
  income_tax_expenses: "Income Tax Expenses",
  net_profit_loss_for_the_year: "Net Profit/(Loss) For The Year",
  basic_eps: "Basic EPS",
  diluted_eps: "Diluted EPS",
};
export const nricBalanceSheetDict: Dict = {
  goodwill_intangible_assets: "Goodwill & Intangible Assets",
  property_and_equipment: "Property and Equipment",
  investment_properties: "Investment Properties",
  deferred_tax_assets: "Deferred Tax Assets",
  investment_in_subsidiaries: "Investment in Subsidiaries",
  investment_in_associates: "Investment in Associates",
  investments: "Investments",
  loans: "Loans",
  reinsurance_assets: "Reinsurance Assets",
  current_tax_assets_net: "Current Tax Assets (Net)",
  insurance_receivables: "Insurance Receivables",
  other_assets: "Other Assets",
  other_financial_assets: "Other Financial Assets",
  cash_and_cash_equivalent: "Cash and Cash Equivalent",
  total_assets: "Total Assets",
  share_capital: "Share Capital",
  share_application_money_pending_allotment:
    "Share Application Money Pending Allotment",
  share_premium: "Share Premium",
  special_reserve: "Special Reserve",
  catastrophe_reserves: "Catastrophe Reserves",
  retained_earnings: "Retained Earnings",
  other_equity: "Other Equity",
  total_equity: "Total Equity",
  provisions: "Provisions",
  gross_insurance_contract_liabilities: "Gross Insurance Contract Liabilities",
  deferred_tax_liabilities: "Deferred Tax Liabilities",
  insurance_payable: "Insurance Payable",
  current_tax_liabilities_net: "Current Tax Liabilities (Net)",
  borrowings: "Borrowings",
  other_liabilities: "Other Liabilities",
  other_financial_liabilities: "Other Financial Liabilities",
  total_liabilities: "Total Liabilities",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const nrmBalanceSheetDict: Dict = {
  property_plant_and_equipment: "Property, Plant and Equipment",
  intangible_assets: "Intangible Assets",
  investment: "Investment",
  right_of_use_asset: "Right-of-Use Asset",
  deferred_tax_asset: "Deferred Tax Asset",
  other_non_current_asset: "Other Non-Current Asset",
  total_non_current_assets: "Total Non Current Assets",
  inventory: "Inventory",
  trade_and_other_receivables: "Trade & Other Receivables",
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  total_current_assets: "Total Current Assets",
  total_assets: "Total Assets",
  share_capital: "Share Capital",
  retained_earnings: "Retained Earnings",
  other_component_of_equity: "Other Component of Equity",
  total_equity: "Total Equity",
  long_term_borrowings: "Long Term Borrowings",
  lease_liability: "Lease Liability",
  other_non_current_liabilities: "Other Non Current Liabilities",
  total_non_current_liabilities: "Total Non Current Liabilities",
  trade_and_other_payables: "Trade and Other Payables",
  employee_benefit_liability: "Employee Benefit Liability",
  short_term_borrowings: "Short Term Borrowings",
  total_current_liabilities: "Total Current Liabilities",
  total_liabilities: "Total Liabilities",
  total_equity_and_liabilities: "Total Equity and Liabilities",
};
export const nrmIncomeStatementDict: Dict = {
  revenue: "Revenue",
  cost_of_sales: "Cost of Sales",
  gross_income: "Gross Income",
  other_income: "Other Income",
  administration_expenses: "Administration Expenses",
  selling_and_distribution_expenses: "Selling & Distribution Expenses",
  ipo_expenses: "IPO Expenses",
  other_expenses: "Other Expenses",
  operating_profit_loss: "Operating Profit/ (Loss)",
  finance_charge: "Finance Charge",
  depreciation: "Depreciation",
  amortization: "Amortization",
  profit_loss_before_tax: "Profit/ (Loss) before Tax",
  less_tax: "Less: Tax",
  current_tax: "Current Tax",
  deferred_tax_income_expense: "Deferred Tax Income (Expense)",
  net_profit_loss_for_year: "Net Profit/ (Loss) For the Year",
};
export const nwclBalanceSheetDict: Dict = {
  property_plant_and_equipment: "Property, plant and equipment",
  capital_work_in_progress: "Capital work in Progress",
  intangible_assets: "Intangible assets",
  right_of_use_assets: "Right of Use Assets",
  deferred_tax_asset: "Deferred tax asset",
  total_non_current_assets: "Total Non-Current Assets",
  trade_receivables: "Trade Receivables",
  cash_and_cash_equivalents: "Cash & cash equivalents",
  bank_balances_other_than_ii_above: "Bank balances other than (II) above",
  current_tax_assets: "Current tax assets",
  other_current_assets: "Other current assets",
  total_current_assets: "Total Current Assets",
  total_assets: "Total Assets",
  equity_share_capital: "Equity share capital",
  promoters_advance: "Promoter's Advance",
  other_equity: "Other equity",
  total_equity: "Total Equity",
  financial_liabilities: "Financial liabilities",
  borrowings: "Borrowings",
  total_non_current_liabilities: "Total Non-Current Liabilities",
  trade_payables: "Trade payables",
  other_financial_liabilities: "Other financial liabilities",
  provisions: "Provisions",
  total_current_liabilities: "Total Current Liabilities",
  total_liabilities: "Total Liabilities",
  total_equity_and_liabilities: "Total Equity & Liabilities",
};
export const nwclIncomeStatementDict: Dict = {
  income: "Income",
  revenue_from_operation: "Revenue from operation",
  other_income: "Other income",
  total_income: "Total income",
  direct_operating_expenses: "Direct Operating Expenses",
  gross_profit: "Gross Profit",
  employee_benefits: "Employee benefits",
  other_expenses: "Other expenses",
  earnings_before_interest_depreciation_and_taxes:
    "Earnings Before Interest, Depreciation and taxes",
  finance_costs: "Finance costs",
  earnings_after_interest_before_depreciation_and_taxes:
    "Earnings after Interest& before Depreciation and taxes",
  depreciation_and_amortization_expense: "Depreciaton and amortization expense",
  net_profit_loss_before_tax: "Net Profit/(Loss) before Tax",
  current_tax: "Current Tax",
  deferred_tax_income_expense: "Deferred Tax Income (Expense)",
  net_profit_loss_after_tax: "Net Profit/(Loss) after Tax",
};

export const dataDict = (
  key: string,
  sector: string | null,
  other: string | null,
): string => {
  if (sector === null) return key;
  if (sector === "others" && other === null) return key;
  let name: string = "";

  switch (sector) {
    case "development_banks":
    case "commercial_banks":
    case "finance":
    case "micro_finance":
      name = {
        ...bankingIncomeStatementDict,
        ...bankingBalanceSheetDict,
        ...bankRatiosDict,
      }[key];
      break;
    case "life_insurance":
    case "non_life_insurance":
      name = {
        ...insuranceIncomeStatementDict,
        ...insuranceBalanceSheetDict,
        ...nonelifeInsuranceRatiosDict,
        ...lifeInsuranceRatiosDict,
      }[key];
      break;
    case "hotels_and_tourism":
      name = { ...htIncomeStatementDict, ...htBalanceSheetDict }[key];
      break;
    case "manufacturing_and_processing":
      name = { ...mpBalanceSheetDict, ...mpIncomeStatementDict }[key];
      break;
    case "investment":
      name = {
        ...investmentIncomeStatementDict,
        ...investmentBalanceSheetDict,
        ...investmentRatiosDict,
      }[key];

      break;
    case "hydro_power":
      name = {
        ...hydroIncomeStatementDict,
        ...hydroBalanceSheetDict,
      }[key];
      break;

    case "others":
      switch (other) {
        case "hrl":
          name = { ...hrlBalanceSheetDict, ...hrlIncomeStatementDict }[key];
          break;
        case "mkcl":
          name = { ...mkchBalanceSheetDict, ...mkchIncomeStatementDict }[key];
          break;
        case "nric":
          name = { ...nricBalanceSheetDict, ...nricIncomeStatementDict }[key];
          break;
        case "nrm":
          name = { ...nrmBalanceSheetDict, ...nrmIncomeStatementDict }[key];
          break;
        case "ntc":
          name = { ...ntcBalanceSheetDict, ...ntcIncomeStatementDict }[key];
          break;
        case "nwcl":
          name = { ...nwclBalanceSheetDict, ...nwclIncomeStatementDict }[key];
          break;
      }
      break;
    default:
      break;
  }
  return name || key;
};
// hydro synonyms 
export const hydroBalanceSheetSynonymsDict = {
  share_capital: ["Equity Share Capital", "Issued Capital", "Paid-up Capital"],
  premium: ["Share Premium", "Additional Paid-in Capital"],
  reserves: ["Retained Earnings", "Accumulated Profits", "Surplus"],
  long_term_liabilities: ["Non-Current Liabilities", "Long-term Debt", "Capital Employed (broader sense)"],
  total_funds: ["Total Capital Employed", "Total Assets", "Total Capital"],
  fixed_assets: ["Property, Plant, and Equipment (PP&E)", "Tangible Assets", "Capital Assets"],
  depreciation: ["Amortization (for intangible assets)", "Wear and Tear (informal)", "Depletion (for resources)"],
  net_fixed_assets: ["Net PP&E", "Book Value of Fixed Assets", "Carrying Value of Fixed Assets"],
  non_core_assets: ["Non-Operating Assets", "Discontinued Operations Assets", "Assets Held for Sale"],
  investments: ["Financial Investments", "Marketable Securities", "Portfolio Investments"],
  work_in_progress: ["Work in Process (WIP)", "Inventory in Process", "Partially Finished Goods"],
  cash: ["Cash and Cash Equivalents", "Liquid Assets", "Bank Balance (specific)"],
  receivables: ["Accounts Receivable", "Trade Receivables", "Debtors"],
  advances_prepayments_loans_deposits_and_other_current_assets: [
    "Other Current Assets",
    "Short-term Receivables and Prepayments",
    "Advances, Prepayments, Loans, Deposits, and Other Current Assets"
  ],
  inventory: ["Stock", "Merchandise Inventory", "Raw Materials", "Finished Goods"],
  total_current_assets: ["Current Assets"],
  short_term_liabilities: ["Current Liabilities", "Short-term Debt"],
  deferred_liabilities: ["Non-Current Deferred Liabilities", "Long-term Deferred Liabilities"],
  total_short_term_liabilities: ["Total Current Liabilities"],
  application_of_funds: ["Uses of Funds", "Asset Side", "Where the money went (informal)"],
};
export const hydroIncomeStatementSynonymsDict = {
  energy_sales: ["Revenue from Energy Sales", "Electricity Sales", "Power Sales", "Sales Revenue"],
  cost_of_production: ["Cost of Goods Sold (COGS)", "Cost of Sales", "Production Costs", "Direct Costs"],
  gross_profit: ["Gross Income", "Gross Margin"],
  dividend_income: ["Dividend Revenue", "Income from Dividends"],
  forex_gain_loss: ["Foreign Exchange Gain or Loss", "Currency Exchange Gain/Loss", "FX Gain/Loss"],
  other_income: ["Non-Operating Income", "Miscellaneous Income", "Secondary Income", "Ancillary Income"],
  admin_expenses: ["Administrative Expenses", "General and Administrative Expenses (G&A)", "Overhead Expenses"],
  operating_profit: ["Earnings Before Interest and Taxes (EBIT)", "Operating Income", "Profit from Operations"],
  interest_expense: ["Interest Cost", "Finance Costs"],
  depreciation: ["Amortization", "Wear and Tear", "Depletion"],
  provisions: ["Allowances", "Reserves (sometimes)", "Estimated Liabilities"],
  profit_before_tax: ["Pre-tax Profit", "Earnings Before Tax (EBT)"],
  taxes: ["Income Tax Expense", "Taxation", "Corporate Taxes"],
  bonus_and_csr: ["Employee Bonuses and Corporate Social Responsibility Expenses", "Bonus Expense", "CSR Expense"],
  net_profit: ["Net Income", "Profit After Tax (PAT)", "Bottom Line (informal)"],
  profitability_ratios: ["Profitability Metrics", "Profit Ratios", "Performance Ratios"],
  earnings_per_share: ["EPS", "Basic EPS"],
  book_value_per_share: ["BVPS", "Net Asset Value per Share (NAVPS - similar)"],
  ebitda: ["Earnings Before Interest, Taxes, Depreciation, and Amortization"], // No direct synonym, explanation instead
  gross_profit_margin: ["Gross Margin Percentage", "Gross Profit Ratio"],
  operating_profit_margin: ["Operating Margin Percentage", "EBIT Margin", "Operating Profit Ratio"],
  net_profit_margin: ["Net Margin Percentage", "Net Profit Ratio", "Profit Margin"],
  management_efficiency_ratios: ["Efficiency Ratios", "Activity Ratios", "Turnover Ratios"],
  return_on_equity: ["ROE", "Return to Shareholders' Equity"],
  return_on_asset: ["ROA", "Return on Total Assets"],
  return_on_capital_employed: ["ROCE", "Return on Capital"],
  debt_equity: ["Debt-to-Equity Ratio", "Gearing Ratio", "Leverage Ratio"],
  current_ratio: ["Liquidity Ratio", "Working Capital Ratio"],
  valuation_ratios: ["Market Ratios", "Stock Ratios", "Investment Ratios"],
  market_cap: ["Market Capitalization", "Equity Market Value", "Stock Market Value"],
  enterprise_value_ev: ["EV", "Total Enterprise Value", "Firm Value (less precise)"],
  price_earnings: ["P/E Ratio", "PE Multiple", "Earnings Multiple"],
  price_book: ["P/B Ratio", "PB Multiple", "Price-to-Book Ratio"],
  price_revenue: ["P/S Ratio", "PS Multiple", "Price-to-Sales Ratio"],
  ev_ebitda: ["EV/EBITDA Multiple", "Enterprise Value to EBITDA Ratio"],
};
